- name: NPM install
  npm: path={{homeDir}}/{{appDir}}/api
  register: npm_finished
  when: git_finished.changed

- name: Start Demo App
  sudo_user: ubuntu
  command: pm2 start index.js --name app chdir={{homeDir}}/{{appDir}}
  ignore_errors: yes