---
- name: GIT | Install package
  apt: pkg="git" state="latest"
  become: yes
  tags:
    - git

- name: Create APP Directory
  file: path={{homeDir}}/{{appDir}} state=directory
  tags:
      -git

- name: GIT | Copy Private Key
  copy: src={{privateKey}} dest={{homeDir}} mode=0600

- name: Git Clone Repo
  git: repo=git@github.com:{{account}}/{{repo}}.git dest={{homeDir}}/{{appDir}} update=yes force=yes accept_hostkey=yes key_file={{homeDir}}/id_rsa
  register: git_finished
  tags:
    -git
