---
- hosts: www
  gather_facts: False

  pre_tasks:
    - debug: msg="Pre tasks section"

    - name: ANSIBLE PYTHON | install python 2
      raw: test -e /usr/bin/python || (apt -qqy update && apt install -qy python-minimal)
      become: yes

    - name: UNPRIVILEGED USERS | Get acl dependency (ansible unprivileged user operations magic)
      apt: pkg="acl"
      become: yes

    - name: gather facts
      setup:

  vars_files:
    - vars.yml
    - secret_vars.yml

  tasks:
    - name: Bootstrap | Install Packages
      include: components/_install_packages.yml

    - name: Bootstrap | Install Node
      include: components/_install_node.yml

    - name: Bootstrap | Clone Project Repo
      include: components/_clone_repo.yml

    - name: Bootstrap | Install PostgreSQL
      include: components/_install_postgres.yml

    - name: Bootstrap | Upstart
      include: components/_upstart.yml